<?php
declare(strict_types=1);

use Migrations\BaseMigration;

class AlignTodosTagsPrimaryKey extends BaseMigration
{
    /**
     * Make (todo_id, tag_id) the real primary key of the join table.
     *
     * The surrogate `id` column made the ORM primary key definition disagree with the
     * database, which allowed duplicate attachment attempts to become silent no-op writes
     * instead of unique-constraint violations.
     */
    public function up(): void
    {
        $this->execute('DELETE FROM todos_tags a USING todos_tags b '
            . 'WHERE a.id > b.id AND a.todo_id = b.todo_id AND a.tag_id = b.tag_id');
        $this->execute('ALTER TABLE todos_tags DROP CONSTRAINT todos_tags_pkey');
        $this->execute('ALTER TABLE todos_tags DROP COLUMN id');
        $this->execute('DROP INDEX IF EXISTS todos_tags_unique');
        $this->execute('ALTER TABLE todos_tags ADD CONSTRAINT todos_tags_pkey PRIMARY KEY (todo_id, tag_id)');
    }

    /**
     * Restore the surrogate primary key and the separate unique index.
     */
    public function down(): void
    {
        $this->execute('ALTER TABLE todos_tags DROP CONSTRAINT todos_tags_pkey');
        $this->execute('ALTER TABLE todos_tags ADD COLUMN id integer GENERATED BY DEFAULT AS IDENTITY');
        $this->execute('ALTER TABLE todos_tags ADD CONSTRAINT todos_tags_pkey PRIMARY KEY (id)');
        $this->execute('CREATE UNIQUE INDEX todos_tags_unique ON todos_tags (todo_id, tag_id)');
    }
}
